### ISSUE TITLE
iOS voice dictation does not work as expected in DTRichTextEditor - either crashing the app or inserting the spoken text multiple times

### ISSUE THREAD

**Issue by slm-2015** [Cocoanetics/DTRichTextEditor#3]
Hi,

I am using the rich text editor (DTRichTextEditor) in our project and are experiencing an issue with the use of the voice dictation feature available on the iOS keyboard.  The problem results in either a crash or the spoken text being inserted multiple times.

Here are the repro steps:
- Embed the rich text editor into a skeleton app that contains a view that holds the DTRichTextEditor component. You can find our example project that [does this here](http://sendfile.pl/pobierz/417814---4VUZ.html).
- Start the app. Start the voice dictation, but do not saying anything for 3 or 4 seconds.  Press done.
  *\* The app crashes with these details:
  DTRichTextEditorView.m line 2263 -[replaceRange:withText:]
  DTRichTextEditorView+Manipulation.m line 886 -[replaceRange:withAttachment:inParagraph:]
  DTRichTextEditorView+Dictation.m line 63 -[dictationRecordingDidEnd]
- Start the app again. Start the voice dictation and say a few sentences.  Hit done.  The text inserted is what was said, but repeated multiple times or just partially inserted.  It seems quite random.

We are testing on iOS 8. xcode 6.3 with iOS sdk 8.3

I'd would like to offer $200 USD to the person who can produce a fix to get voice dictation working properly.  Transfer of payment on a successful code review from Oliver and subject to final testing within my project.

Many thanks,
Simon.

**Comment by blundgren** [comment]
There appears to be a couple of issues involved here:
1. Since the protocol method **insertDictationResultPlaceholder** was not implemented, UIKit was inserting its own default placeholder, which was conflicting with the custom placeholder inserted by **dictationRecordingDidEnd**. By creating the custom placeholder in **insertDictationResultPlaceholder** (and removing it in **removeDictationResultPlaceholder**) we're working with the system instead of against it.
2. There may have been a misunderstanding about the purpose of the **insertDictationResult** protocol method. **insertDictationResult** is invoked when there are multiple possible interpretations of the dictation. The existing implementation was inserting all of them, causing the repetition you were seeing. By simply not implementing this method, the default behavior will insert the "most likely" interpretation. Perhaps a future enhancement could offer some UI element to select among the possibilities.
3. As a bonus, there was an unrelated pair of typos in **_inputDelegateSelectionDidChange** and **_inputDelegateTextDidChange** which were invoking their "WillChange" counterparts rather than "DidChange".

pull request: https://github.com/Cocoanetics/DTRichTextEditor/pull/4

Hope this helps.
  --Brian

**Comment by odrobnik** [comment]
@slm-2015 Please test the pull request on a variety of devices OS versions. I think it is amazing.

**Comment by slm-2015** [comment]
@Cocoanetics, I agree - an incredible analysis.  Thanks very much @blundgren!  Tomorrow we will pull your changes and test them across a range of devices / OS combos.  We will come back and update this thread as soon as possible. Thanks again.

**Comment by slm-2015** [comment]
@Cocoanetics @blundgren 

The suggested pull request #4 works very well and solves the described problems nicely. Found an additional small issue with dictation placeholder not being removed after dictation failed. Created a pull request to cover that too #5. 

If we can verify that #5 looks good, that will conclude this issue nicely!  @blundgren do you please have an email address which I can reach you on and arrange payment once @Cocoanetics confirms he is happy with all the changes?

Cheers all

**Comment by blundgren** [comment]
Glad to hear it. You can reach me at: brianl _at_ pro-ns _dot_ net.

**Comment by odrobnik** [comment]
The pull request #5 apparently has conflicts, probably because it was not based on develop after merging #4.

**Comment by slm-2015** [comment]
fixed merge conflict - thanks @Cocoanetics.

@blundgren I have sent you an email re arranging payment.  thanks v much.

**Comment by odrobnik** [comment]
ok, @slm-2015 I merged it all. Is the current state of develop good to be released?

**Comment by slm-2015** [comment]
Hi @Cocoanetics, thanks very much.

Our testing is showing everything to be working well, thanks.  @blundgren and I have exchanged emails and we have made the bounty payment.  So I believe we are good to release.

Cheers and thanks,
Simon.

**Comment by odrobnik** [comment]
Released in 1.6.11: https://github.com/Cocoanetics/DTRichTextEditor/releases/tag/1.6.11
